let year2022 = JSON.parse(`[
    {
      "godina": 2022,
      "mjesec": "siječanj",
      "prodaja": [
        { "marka": "Toyota", "broj_prodanih": 158676 },
        { "marka": "GM", "broj_prodanih": 142574 },
        { "marka": "Ford", "broj_prodanih": 142445 },
        { "marka": "Stellantis", "broj_prodanih": 125896 },
        { "marka": "Honda", "broj_prodanih": 73949 },
        { "marka": "Nissan", "broj_prodanih": 59742 },
        { "marka": "Hyundai", "broj_prodanih": 51510 },
        { "marka": "Subaru", "broj_prodanih": 44158 },
        { "marka": "Kia", "broj_prodanih": 42488 },
        { "marka": "Tesla", "broj_prodanih": 40165 },
        { "marka": "VW", "broj_prodanih": 22092 },
        { "marka": "BMW", "broj_prodanih": 21514 },
        { "marka": "Mazda", "broj_prodanih": 21079 },
        { "marka": "Mercedes", "broj_prodanih": 20400 },
        { "marka": "Audi", "broj_prodanih": 11427 },
        { "marka": "Mitsubishi", "broj_prodanih": 6475 },
        { "marka": "Volvo", "broj_prodanih": 5742 },
        { "marka": "Porsche", "broj_prodanih": 4077 },
        { "marka": "Land Rover", "broj_prodanih": 4070 },
        { "marka": "Mini", "broj_prodanih": 2441 },
        { "marka": "Jaguar", "broj_prodanih": 475 },
        { "marka": "Polestar", "broj_prodanih": 398 },
        { "marka": "Lucid Motors", "broj_prodanih": 299 },
        { "marka": "Rivian", "broj_prodanih": 214 },
        { "marka": "Karma", "broj_prodanih": 16 },
        { "marka": "Ostali", "broj_prodanih": 661 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 50480 },
        { "model": "Ram P/U", "broj_prodanih": 41283 },
        { "model": "Chevrloet Silverado", "broj_prodanih": 34374 },
        { "model": "Toyota RAV4", "broj_prodanih": 29935 },
        { "model": "Jeep Grand Cherokee", "broj_prodanih": 23693 },
        { "model": "Tesla Model Y", "broj_prodanih": 20665 },
        { "model": "Toyota Camry", "broj_prodanih": 20212 },
        { "model": "Toyota Highlander", "broj_prodanih": 17035 },
        { "model": "GMC Sierra", "broj_prodanih": 16631 },
        { "model": "Ford Explorer", "broj_prodanih": 16255 }
      ]
    },
  
    {
      "godina": 2022,
      "mjesec": "veljača",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 161718 },
        { "marka": "Toyota", "broj_prodanih": 160645 },
        { "marka": "Stellantis", "broj_prodanih": 128229 },
        { "marka": "Ford", "broj_prodanih": 125896 },
        { "marka": "Honda", "broj_prodanih": 84394 },
        { "marka": "Nissan", "broj_prodanih": 61674 },
        { "marka": "Hyundai", "broj_prodanih": 55906 },
        { "marka": "Kia", "broj_prodanih": 49182 },
        { "marka": "Subaru", "broj_prodanih": 44866 },
        { "marka": "Tesla", "broj_prodanih": 42742 },
        { "marka": "Mazda", "broj_prodanih": 28166 },
        { "marka": "BMW", "broj_prodanih": 23977 },
        { "marka": "VW", "broj_prodanih": 20655 },
        { "marka": "Mercedes", "broj_prodanih": 19237 },
        { "marka": "Audi", "broj_prodanih": 12472 },
        { "marka": "Mitsubishi", "broj_prodanih": 8728 },
        { "marka": "Volvo", "broj_prodanih": 6219 },
        { "marka": "Land Rover", "broj_prodanih": 5273 },
        { "marka": "Porsche", "broj_prodanih": 2854 },
        { "marka": "Mini", "broj_prodanih": 2097 },
        { "marka": "Jaguar", "broj_prodanih": 783 },
        { "marka": "Polestar", "broj_prodanih": 428 },
        { "marka": "Rivian", "broj_prodanih": 238 },
        { "marka": "Lucid Motors", "broj_prodanih": 135 },
        { "marka": "Karma", "broj_prodanih": 21 },
        { "marka": "Ostali", "broj_prodanih": 583 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 45252 },
        { "model": "Ram P/U", "broj_prodanih": 43184 },
        { "model": "Chevrloet Silverado", "broj_prodanih": 38588 },
        { "model": "Toyota RAV4", "broj_prodanih": 33051 },
        { "model": "Jeep Grand Cherokee", "broj_prodanih": 25000 },
        { "model": "Toyota Highlander", "broj_prodanih": 23102 },
        { "model": "Tesla Model Y", "broj_prodanih": 21242 },
        { "model": "GMC Sierra", "broj_prodanih": 18679 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 17834 },
        { "model": "Mazda CX-5", "broj_prodanih": 16404 }
      ]
    },
  
    {
      "godina": 2022,
      "mjesec": "ožujak",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 204830 },
        { "marka": "Toyota", "broj_prodanih": 195271 },
        { "marka": "Ford", "broj_prodanih": 158500 },
        { "marka": "Stellantis", "broj_prodanih": 144021 },
        { "marka": "Honda", "broj_prodanih": 108075 },
        { "marka": "Nissan", "broj_prodanih": 79655 },
        { "marka": "Hyundai", "broj_prodanih": 63983 },
        { "marka": "Kia", "broj_prodanih": 59524 },
        { "marka": "Tesla", "broj_prodanih": 47953 },
        { "marka": "Subaru", "broj_prodanih": 43322 },
        { "marka": "Mazda", "broj_prodanih": 33023 },
        { "marka": "BMW", "broj_prodanih": 28223 },
        { "marka": "VW", "broj_prodanih": 22246 },
        { "marka": "Mercedes", "broj_prodanih": 16987 },
        { "marka": "Audi", "broj_prodanih": 11606 },
        { "marka": "Mitsubishi", "broj_prodanih": 11197 },
        { "marka": "Volvo", "broj_prodanih": 5610 },
        { "marka": "Land Rover", "broj_prodanih": 5355 },
        { "marka": "Porsche", "broj_prodanih": 4860 },
        { "marka": "Mini", "broj_prodanih": 2338 },
        { "marka": "Jaguar", "broj_prodanih": 1098 },
        { "marka": "Polestar", "broj_prodanih": 684 },
        { "marka": "Rivian", "broj_prodanih": 268 },
        { "marka": "Lucid Motors", "broj_prodanih": 150 },
        { "marka": "Karma", "broj_prodanih": 23 },
        { "marka": "Ostali", "broj_prodanih": 767 }
      ],
      "modeli": [
        { "model": "Chevrolet Silverado", "broj_prodanih": 45834 },
        { "model": "Ford F-Series", "broj_prodanih": 44906 },
        { "model": "RAM P/U", "broj_prodanih": 42649 },
        { "model": "Toyota RAV4", "broj_prodanih": 38206 },
        { "model": "Honda CR-V", "broj_prodanih": 29943 },
        { "model": "Jeep Gran Cherokee", "broj_prodanih": 26424 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 26025 },
        { "model": "Toyota Highlander", "broj_prodanih": 25889 },
        { "model": "Toyota Camry", "broj_prodanih": 25457 },
        { "model": "Tesla Model Y", "broj_prodanih": 24953 }
      ]
    },
  
    {
      "godina": 2022,
      "mjesec": "travanj",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 200981 },
        { "marka": "Toyota", "broj_prodanih": 186510 },
        { "marka": "Ford", "broj_prodanih": 175942 },
        { "marka": "Stellantis", "broj_prodanih": 143645 },
        { "marka": "Honda", "broj_prodanih": 93250 },
        { "marka": "Nissan", "broj_prodanih": 74668 },
        { "marka": "Hyundai", "broj_prodanih": 66707 },
        { "marka": "Kia", "broj_prodanih": 59063 },
        { "marka": "Tesla", "broj_prodanih": 48432 },
        { "marka": "Subaru", "broj_prodanih": 45748 },
        { "marka": "Mercedes", "broj_prodanih": 31065 },
        { "marka": "Mazda", "broj_prodanih": 30093 },
        { "marka": "BMW", "broj_prodanih": 27289 },
        { "marka": "VW", "broj_prodanih": 25476 },
        { "marka": "Audi", "broj_prodanih": 14427 },
        { "marka": "Volvo", "broj_prodanih": 10022 },
        { "marka": "Mitsubishi", "broj_prodanih": 8994 },
        { "marka": "Porsche", "broj_prodanih": 5585 },
        { "marka": "Land Rover", "broj_prodanih": 4125 },
        { "marka": "Mini", "broj_prodanih": 1262 },
        { "marka": "Jaguar", "broj_prodanih": 823 },
        { "marka": "Polestar", "broj_prodanih": 675 },
        { "marka": "Rivian", "broj_prodanih": 459 },
        { "marka": "Lucid Motors", "broj_prodanih": 148 },
        { "marka": "Karma", "broj_prodanih": 25 },
        { "marka": "Ostali", "broj_prodanih": 810 }
      ],
      "modeli": [
        { "model": "Chevrolet Silverado", "broj_prodanih": 52021 },
        { "model": "Ford F-Series", "broj_prodanih": 51517 },
        { "model": "RAM P/U", "broj_prodanih": 42910 },
        { "model": "Toyota RAV4", "broj_prodanih": 34502 },
        { "model": "Toyota Camry", "broj_prodanih": 26576 },
        { "model": "Tesla Model Y", "broj_prodanih": 25432 },
        { "model": "Jeep Gran Cherokee", "broj_prodanih": 23266 },
        { "model": "Toyota Corolla", "broj_prodanih": 22985 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 22815 },
        { "model": "GMC Sierra", "broj_prodanih": 21224 }
      ]
    },
  
    {
      "godina": 2022,
      "mjesec": "svibanj",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 240095 },
        { "marka": "Toyota", "broj_prodanih": 241003 },
        { "marka": "Ford", "broj_prodanih": 160520 },
        { "marka": "Stellantis", "broj_prodanih": 183628 },
        { "marka": "Honda", "broj_prodanih": 176815 },
        { "marka": "Hyundai", "broj_prodanih": 93745 },
        { "marka": "Kia", "broj_prodanih": 80298 },
        { "marka": "Nissan", "broj_prodanih": 110374 },
        { "marka": "Tesla", "broj_prodanih": 27443 },
        { "marka": "Subaru", "broj_prodanih": 56558 },
        { "marka": "VW", "broj_prodanih": 44452 },
        { "marka": "BMW", "broj_prodanih": 35642 },
        { "marka": "Mercedes", "broj_prodanih": 33254 },
        { "marka": "Audi", "broj_prodanih": 22051 },
        { "marka": "Mazda", "broj_prodanih": 42187 },
        { "marka": "Volvo", "broj_prodanih": 13221 },
        { "marka": "Mitsubishi", "broj_prodanih": 9403 },
        { "marka": "Porsche", "broj_prodanih": 6820 },
        { "marka": "Land Rover", "broj_prodanih": 7519 },
        { "marka": "Mini", "broj_prodanih": 3457 },
        { "marka": "Polestar", "broj_prodanih": 51 },
        { "marka": "Jaguar", "broj_prodanih": 2085 },
        { "marka": "Rivian", "broj_prodanih": 0 },
        { "marka": "Lucid Motors", "broj_prodanih": 0 },
        { "marka": "Karma", "broj_prodanih": 10 },
        { "marka": "Ostali", "broj_prodanih": 827 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 49454 },
        { "model": "Chevrolet Silverado", "broj_prodanih": 44461 },
        { "model": "RAM P/U", "broj_prodanih": 36399 },
        { "model": "Toyota RAV4", "broj_prodanih": 33233 },
        { "model": "Toyota Camry", "broj_prodanih": 24948 },
        { "model": "Tesla Model Y", "broj_prodanih": 22506 },
        { "model": "Toyota Corolla", "broj_prodanih": 22211 },
        { "model": "GMC Sierra", "broj_prodanih": 21182 },
        { "model": "Ford Explorer", "broj_prodanih": 19594 },
        { "model": "Jeep Gran Cherokee", "broj_prodanih": 19418 }
      ]
    },
  
    {
      "godina": 2022,
      "mjesec": "lipanj",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 199755 },
        { "marka": "Toyota", "broj_prodanih": 167823 },
        { "marka": "Ford", "broj_prodanih": 151182 },
        { "marka": "Stellantis", "broj_prodanih": 135009 },
        { "marka": "Honda", "broj_prodanih": 71048 },
        { "marka": "Hyundai", "broj_prodanih": 67597 },
        { "marka": "Kia", "broj_prodanih": 65142 },
        { "marka": "Nissan", "broj_prodanih": 55122 },
        { "marka": "Subaru", "broj_prodanih": 43175 },
        { "marka": "Tesla", "broj_prodanih": 42757 },
        { "marka": "Mercedes", "broj_prodanih": 32494 },
        { "marka": "VW", "broj_prodanih": 27103 },
        { "marka": "BMW", "broj_prodanih": 26324 },
        { "marka": "Audi", "broj_prodanih": 17008 },
        { "marka": "Mazda", "broj_prodanih": 15130 },
        { "marka": "Volvo", "broj_prodanih": 8434 },
        { "marka": "Porsche", "broj_prodanih": 6407 },
        { "marka": "Mitsubishi", "broj_prodanih": 5855 },
        { "marka": "Land Rover", "broj_prodanih": 3528 },
        { "marka": "Mini", "broj_prodanih": 2291 },
        { "marka": "Rivian", "broj_prodanih": 1468 },
        { "marka": "Polestar", "broj_prodanih": 742 },
        { "marka": "Jaguar", "broj_prodanih": 641 },
        { "marka": "Lucid Motors", "broj_prodanih": 201 },
        { "marka": "Karma", "broj_prodanih": 1020 },
        { "marka": "Ostali", "broj_prodanih": 1023 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 57673 },
        { "model": "Chevrolet Silverado", "broj_prodanih": 44238 },
        { "model": "RAM P/U", "broj_prodanih": 38558 },
        { "model": "Toyota RAV4", "broj_prodanih": 31958 },
        { "model": "Toyota Camry", "broj_prodanih": 22896 },
        { "model": "Honda CR-V", "broj_prodanih": 22865 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 20914 },
        { "model": "Tesla Model Y", "broj_prodanih": 20257 },
        { "model": "Toyota Tacoma", "broj_prodanih": 20150 },
        { "model": "GMC Sierra", "broj_prodanih": 19915 }
      ]
    }
  ]
  `)

let year2021 = JSON.parse(`[
    {
      "godina": 2021,
      "mjesec": "siječanj",
      "prodaja": [
        { "marka": "Toyota", "broj_prodanih": 167936 },
        { "marka": "GM", "broj_prodanih": 201954 },
        { "marka": "Ford", "broj_prodanih": 142577 },
        { "marka": "Stellantis", "broj_prodanih": 134942 },
        { "marka": "Honda", "broj_prodanih": 92225 },
        { "marka": "Nissan", "broj_prodanih": 71081 },
        { "marka": "Hyundai", "broj_prodanih": 46208 },
        { "marka": "Subaru", "broj_prodanih": 46400 },
        { "marka": "Kia", "broj_prodanih": 44965 },
        { "marka": "Tesla", "broj_prodanih": 24700 },
        { "marka": "VW", "broj_prodanih": 24165 },
        { "marka": "BMW", "broj_prodanih": 17659 },
        { "marka": "Mazda", "broj_prodanih": 25259 },
        { "marka": "Mercedes", "broj_prodanih": 27722 },
        { "marka": "Audi", "broj_prodanih": 15417 },
        { "marka": "Mitsubishi", "broj_prodanih": 4812 },
        { "marka": "Volvo", "broj_prodanih": 8151 },
        { "marka": "Porsche", "broj_prodanih": 5355 },
        { "marka": "Land Rover", "broj_prodanih": 7267 },
        { "marka": "Mini", "broj_prodanih": 1991 },
        { "marka": "Jaguar", "broj_prodanih": 954 },
        { "marka": "Polestar", "broj_prodanih": 0 },
        { "marka": "Lucid Motors", "broj_prodanih": 0 },
        { "marka": "Rivian", "broj_prodanih": 0 },
        { "marka": "Karma", "broj_prodanih": 0 },
        { "marka": "Ostali", "broj_prodanih": 622 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 55276 },
        { "model": "Ram P/U", "broj_prodanih": 42493 },
        { "model": "Chevrloet Silverado", "broj_prodanih": 37824 },
        { "model": "Toyota RAV4", "broj_prodanih": 31671 },
        { "model": "Jeep Grand Cherokee", "broj_prodanih": 15388 },
        { "model": "Tesla Model Y", "broj_prodanih": 15000 },
        { "model": "Toyota Camry", "broj_prodanih": 21790 },
        { "model": "Toyota Highlander", "broj_prodanih": 17511 },
        { "model": "GMC Sierra", "broj_prodanih": 19104 },
        { "model": "Ford Explorer", "broj_prodanih": 18095 }
      ]
    },
  
    {
      "godina": 2021,
      "mjesec": "veljača",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 191846 },
        { "marka": "Toyota", "broj_prodanih": 184249 },
        { "marka": "Stellantis", "broj_prodanih": 152378 },
        { "marka": "Ford", "broj_prodanih": 161834 },
        { "marka": "Honda", "broj_prodanih": 106328 },
        { "marka": "Nissan", "broj_prodanih": 86138 },
        { "marka": "Hyundai", "broj_prodanih": 50735 },
        { "marka": "Kia", "broj_prodanih": 48062 },
        { "marka": "Subaru", "broj_prodanih": 48300 },
        { "marka": "Tesla", "broj_prodanih": 21550 },
        { "marka": "Mazda", "broj_prodanih": 26008 },
        { "marka": "BMW", "broj_prodanih": 24638 },
        { "marka": "VW", "broj_prodanih": 25769 },
        { "marka": "Mercedes", "broj_prodanih": 29915 },
        { "marka": "Audi", "broj_prodanih": 16819 },
        { "marka": "Mitsubishi", "broj_prodanih": 8442 },
        { "marka": "Volvo", "broj_prodanih": 9164 },
        { "marka": "Land Rover", "broj_prodanih": 7443 },
        { "marka": "Porsche", "broj_prodanih": 5779 },
        { "marka": "Mini", "broj_prodanih": 1669 },
        { "marka": "Jaguar", "broj_prodanih": 1274 },
        { "marka": "Polestar", "broj_prodanih": 0 },
        { "marka": "Rivian", "broj_prodanih": 0 },
        { "marka": "Lucid Motors", "broj_prodanih": 0 },
        { "marka": "Karma", "broj_prodanih": 0 },
        { "marka": "Ostali", "broj_prodanih": 577 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 67478 },
        { "model": "Ram P/U", "broj_prodanih": 49041 },
        { "model": "Chevrloet Silverado", "broj_prodanih": 36580 },
        { "model": "Toyota RAV4", "broj_prodanih": 36157 },
        { "model": "Jeep Grand Cherokee", "broj_prodanih": 17673 },
        { "model": "Toyota Highlander", "broj_prodanih": 19573 },
        { "model": "Tesla Model Y", "broj_prodanih": 10050 },
        { "model": "GMC Sierra", "broj_prodanih": 18459 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 20164 },
        { "model": "Mazda CX-5", "broj_prodanih": 12087 }
      ]
    },
  
    {
      "godina": 2021,
      "mjesec": "ožujak",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 245606 },
        { "marka": "Toyota", "broj_prodanih": 250881 },
        { "marka": "Ford", "broj_prodanih": 213300 },
        { "marka": "Stellantis", "broj_prodanih": 183994 },
        { "marka": "Honda", "broj_prodanih": 148538 },
        { "marka": "Nissan", "broj_prodanih": 128334 },
        { "marka": "Hyundai", "broj_prodanih": 78409 },
        { "marka": "Kia", "broj_prodanih": 66523 },
        { "marka": "Tesla", "broj_prodanih": 23050 },
        { "marka": "Subaru", "broj_prodanih": 65726 },
        { "marka": "Mazda", "broj_prodanih": 31991 },
        { "marka": "BMW", "broj_prodanih": 29136 },
        { "marka": "VW", "broj_prodanih": 40919 },
        { "marka": "Mercedes", "broj_prodanih": 32278 },
        { "marka": "Audi", "broj_prodanih": 22604 },
        { "marka": "Mitsubishi", "broj_prodanih": 14977 },
        { "marka": "Volvo", "broj_prodanih": 9924 },
        { "marka": "Land Rover", "broj_prodanih": 9010 },
        { "marka": "Porsche", "broj_prodanih": 6234 },
        { "marka": "Mini", "broj_prodanih": 2625 },
        { "marka": "Jaguar", "broj_prodanih": 2002 },
        { "marka": "Polestar", "broj_prodanih": 118 },
        { "marka": "Rivian", "broj_prodanih": 0 },
        { "marka": "Lucid Motors", "broj_prodanih": 0 },
        { "marka": "Karma", "broj_prodanih": 14 },
        { "marka": "Ostali", "broj_prodanih": 945 }
      ],
      "modeli": [
        { "model": "Chevrolet Silverado", "broj_prodanih": 50300 },
        { "model": "Ford F-Series", "broj_prodanih": 84043 },
        { "model": "RAM P/U", "broj_prodanih": 57302 },
        { "model": "Toyota RAV4", "broj_prodanih": 46427 },
        { "model": "Honda CR-V", "broj_prodanih": 37711 },
        { "model": "Jeep Gran Cherokee", "broj_prodanih": 22137 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 20796 },
        { "model": "Toyota Highlander", "broj_prodanih": 26747 },
        { "model": "Toyota Camry", "broj_prodanih": 31717 },
        { "model": "Tesla Model Y", "broj_prodanih": 14450 }
      ]
    },
  
    {
      "godina": 2021,
      "mjesec": "travanj",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 238819 },
        { "marka": "Toyota", "broj_prodanih": 238089 },
        { "marka": "Ford", "broj_prodanih": 197063 },
        { "marka": "Stellantis", "broj_prodanih": 166610 },
        { "marka": "Honda", "broj_prodanih": 156482 },
        { "marka": "Nissan", "broj_prodanih": 99132 },
        { "marka": "Hyundai", "broj_prodanih": 80817 },
        { "marka": "Kia", "broj_prodanih": 70177 },
        { "marka": "Tesla", "broj_prodanih": 25918 },
        { "marka": "Subaru", "broj_prodanih": 61389 },
        { "marka": "Mercedes", "broj_prodanih": 31772 },
        { "marka": "Mazda", "broj_prodanih": 31117 },
        { "marka": "BMW", "broj_prodanih": 29240 },
        { "marka": "VW", "broj_prodanih": 42354 },
        { "marka": "Audi", "broj_prodanih": 23586 },
        { "marka": "Volvo", "broj_prodanih": 11036 },
        { "marka": "Mitsubishi", "broj_prodanih": 7611 },
        { "marka": "Porsche", "broj_prodanih": 6516 },
        { "marka": "Land Rover", "broj_prodanih": 8283 },
        { "marka": "Mini", "broj_prodanih": 2835 },
        { "marka": "Jaguar", "broj_prodanih": 1853 },
        { "marka": "Polestar", "broj_prodanih": 49 },
        { "marka": "Rivian", "broj_prodanih": 0 },
        { "marka": "Lucid Motors", "broj_prodanih": 0 },
        { "marka": "Karma", "broj_prodanih": 9 },
        { "marka": "Ostali", "broj_prodanih": 737 }
      ],
      "modeli": [
        { "model": "Chevrolet Silverado", "broj_prodanih": 50922 },
        { "model": "Ford F-Series", "broj_prodanih": 66302 },
        { "model": "RAM P/U", "broj_prodanih": 52446 },
        { "model": "Toyota RAV4", "broj_prodanih": 39163 },
        { "model": "Toyota Camry", "broj_prodanih": 30463 },
        { "model": "Tesla Model Y", "broj_prodanih": 6600 },
        { "model": "Jeep Gran Cherokee", "broj_prodanih": 17771 },
        { "model": "Toyota Corolla", "broj_prodanih": 29365 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 21061 },
        { "model": "GMC Sierra", "broj_prodanih": 26986 }
      ]
    },
  
    {
      "godina": 2021,
      "mjesec": "svibanj",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 240095 },
        { "marka": "Toyota", "broj_prodanih": 241003 },
        { "marka": "Ford", "broj_prodanih": 160520 },
        { "marka": "Stellantis", "broj_prodanih": 183628 },
        { "marka": "Honda", "broj_prodanih": 176815 },
        { "marka": "Hyundai", "broj_prodanih": 93745 },
        { "marka": "Kia", "broj_prodanih": 80298 },
        { "marka": "Nissan", "broj_prodanih": 110374 },
        { "marka": "Tesla", "broj_prodanih": 27443 },
        { "marka": "Subaru", "broj_prodanih": 56558 },
        { "marka": "VW", "broj_prodanih": 44452 },
        { "marka": "BMW", "broj_prodanih": 35642 },
        { "marka": "Mercedes", "broj_prodanih": 33254 },
        { "marka": "Audi", "broj_prodanih": 22051 },
        { "marka": "Mazda", "broj_prodanih": 42187 },
        { "marka": "Volvo", "broj_prodanih": 13221 },
        { "marka": "Mitsubishi", "broj_prodanih": 9403 },
        { "marka": "Porsche", "broj_prodanih": 6820 },
        { "marka": "Land Rover", "broj_prodanih": 7519 },
        { "marka": "Mini", "broj_prodanih": 3457 },
        { "marka": "Polestar", "broj_prodanih": 51 },
        { "marka": "Jaguar", "broj_prodanih": 2085 },
        { "marka": "Rivian", "broj_prodanih": 0 },
        { "marka": "Lucid Motors", "broj_prodanih": 0 },
        { "marka": "Karma", "broj_prodanih": 10 },
        { "marka": "Ostali", "broj_prodanih": 827 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 46260 },
        { "model": "Chevrolet Silverado", "broj_prodanih": 56499 },
        { "model": "RAM P/U", "broj_prodanih": 62525 },
        { "model": "Toyota RAV4", "broj_prodanih": 28963 },
        { "model": "Toyota Camry", "broj_prodanih": 36085 },
        { "model": "Tesla Model Y", "broj_prodanih": 14700 },
        { "model": "Toyota Corolla", "broj_prodanih": 28592 },
        { "model": "GMC Sierra", "broj_prodanih": 25486 },
        { "model": "Ford Explorer", "broj_prodanih": 16512 },
        { "model": "Jeep Gran Cherokee", "broj_prodanih": 21630 }
      ]
    },
  
    {
      "godina": 2021,
      "mjesec": "lipanj",
      "prodaja": [
        { "marka": "GM", "broj_prodanih": 204782 },
        { "marka": "Toyota", "broj_prodanih": 209721 },
        { "marka": "Ford", "broj_prodanih": 114677 },
        { "marka": "Stellantis", "broj_prodanih": 137003 },
        { "marka": "Honda", "broj_prodanih": 153122 },
        { "marka": "Hyundai", "broj_prodanih": 76519 },
        { "marka": "Kia", "broj_prodanih": 68486 },
        { "marka": "Nissan", "broj_prodanih": 88642 },
        { "marka": "Subaru", "broj_prodanih": 42877 },
        { "marka": "Tesla", "broj_prodanih": 22869 },
        { "marka": "Mercedes", "broj_prodanih": 27417 },
        { "marka": "VW", "broj_prodanih": 33714 },
        { "marka": "BMW", "broj_prodanih": 31697 },
        { "marka": "Audi", "broj_prodanih": 21358 },
        { "marka": "Mazda", "broj_prodanih": 32605 },
        { "marka": "Volvo", "broj_prodanih": 12258 },
        { "marka": "Porsche", "broj_prodanih": 5622 },
        { "marka": "Mitsubishi", "broj_prodanih": 8132 },
        { "marka": "Land Rover", "broj_prodanih": 6972 },
        { "marka": "Mini", "broj_prodanih": 3048 },
        { "marka": "Rivian", "broj_prodanih": 0 },
        { "marka": "Polestar", "broj_prodanih": 48 },
        { "marka": "Jaguar", "broj_prodanih": 1553 },
        { "marka": "Lucid Motors", "broj_prodanih": 0 },
        { "marka": "Karma", "broj_prodanih": 0 },
        { "marka": "Ostali", "broj_prodanih": 869 }
      ],
      "modeli": [
        { "model": "Ford F-Series", "broj_prodanih": 45673 },
        { "model": "Chevrolet Silverado", "broj_prodanih": 54285 },
        { "model": "RAM P/U", "broj_prodanih": 49261 },
        { "model": "Toyota RAV4", "broj_prodanih": 38814 },
        { "model": "Toyota Camry", "broj_prodanih": 32972 },
        { "model": "Honda CR-V", "broj_prodanih": 36564 },
        { "model": "Chevrolet Equinox", "broj_prodanih": 14000 },
        { "model": "Tesla Model Y", "broj_prodanih": 12000 },
        { "model": "Toyota Tacoma", "broj_prodanih": 26240 },
        { "model": "GMC Sierra", "broj_prodanih": 23023 }
      ]
    }
  ]
  `)
